stages:
  - lint
  - test


lint-backend:
  image: gradle:8.5-jdk21
  stage: lint
  script:
    - cd BoggleSpringBoot
    - ./gradlew clean pmdMain pmdTest
  artifacts:
    when: always
    paths:
      - build/reports/pmd/

test-backend:
  image: gradle:8.5-jdk21
  stage: test
  script:
    - cd BoggleSpringBoot
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - BoggleSpringBoot/build/test-results
      - BoggleSpringBoot/build/reports/tests

lint-frontend:
  image: node:20
  stage: lint
  script:
    - cd frontend
    - npm ci
    - npm run lint

test-frontend:
  image: node:20
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm run test -- --run

