stages:
  - lint

lint-backend:
  image: gradle:8.5-jdk17
  stage: lint
  script:
    - cd BoggleSpringBoot
    - ./gradlew check

lint-frontend:
  image: node:20
  stage: lint
  script:
    - cd frontend
    - npm install
    - npm run lint